apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: null
  generation: 1
  labels:
    app: enrollments-app
  name: enrollments-app
  selfLink: /apis/image.openshift.io/v1/namespaces/mongodb/imagestreams/enrollments-app
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/enrollments-app
